# Module containing the user preferences class which loads the userprefs.txt
# This file could either be manually edited or generated by a gui prog.
# This module owns the user preferences.
# We might prefer at a later date to have these values set on a per image basis.
# Then we could store these in a database instead of a plain text file.
# This module should be in charge of ensuring that the font selected exsists
# and default to an alternative if not. It should also check that the size
# is valid.
#
# Font Size can take the range ? - ?
#
# Font can be any True Type Font or "random"
#
# image locations are denoted by numers 1-9.
# 1 = Top left, 2 = Top Centered, 3 = Top Right
# 4 = Middle Left, 5 = Middle Centered, 6 = Middle Right
# 7 = Bottom left, 8 = Bottom Centered, 9 = Bottom right
#

class Userpreferences():
    def __init__(self):
        self.userpreferences = []
        self.loaduserpreferences()
    
    def getuserpreferences(self):
        return self.userpreferences
    
    def loaduserpreferences(self):
        try:
            with open("userprefs.txt") as self.f:
                self.userpreferences = self.f.readlines()
        except Exception:
            print("failed to load userprefs.txt")

#mypreferences = Userpreferences()
#print(mypreferences.getuserpreferences()[2])